name: Sync Chart.yaml Changes to Docs Repo

on:
  push:
    paths:
      - 'Chart.yaml'  # Trigger workflow only if Chart.yaml is changed
    branches:
      - main  # Or whatever branch you are working with

jobs:
  sync-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout getversion repository
      uses: actions/checkout@v2
    
    - name: Set up Git
      run: |
        git config user.name "Your Name"
        git config user.email "your-email@example.com"

    - name: Clone docs repository
      run: |
        git clone https://github.com/ramyerubandi1/docs.git
        cd docs
        git remote set-url origin https://github.com/ramyerubandi1/docs.git

    - name: Copy Chart.yaml to docs repo
      run: |
        cp Chart.yaml ../docs/charts/nginx/
    
    - name: Commit and push changes to docs repo
      run: |
        cd docs
        git add charts/nginx/Chart.yaml
        git commit -m "Update nginx Chart.yaml from getversion repository"
        git push origin main  # Or the branch you want to push to
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
