name: Sync Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'Chart.yaml'  # Triggers only when Chart.yaml changes in getversion repo

jobs:
  sync_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `docs` repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch `Chart.yaml` from `getversion`
        run: |
          curl -sL https://raw.githubusercontent.com/ramyerubandi1/getversion/main/charts/nginx/Chart.yaml -o getversion_Chart.yaml

      - name: Compare `Chart.yaml` files
        run: |
          if ! cmp -s getversion_Chart.yaml charts/nginx/Chart.yaml; then
            echo "Chart.yaml has changed. Updating..."
            cp getversion_Chart.yaml charts/nginx/Chart.yaml
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
          fi

      - name: Commit and push changes
        if: env.CHART_UPDATED == 'true'
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add charts/nginx/Chart.yaml
          git commit -m "Sync Chart.yaml from getversion repo"
          git push origin main
