name: Sync Chart.yaml to docs

on:
  push:
    branches:
      - main
    paths:
      - 'Chart.yaml'  # Trigger only when Chart.yaml changes

jobs:
  sync_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `docs` repository
        uses: actions/checkout@v3
        with:
          repository: ramyerubandi1/docs
          token: ${{ secrets.GH_PAT }}  # Ensure this PAT has write access to docs repo

      - name: Fetch latest `Chart.yaml` from `getversion`
        run: |
          if [ -f charts/nginx/Chart.yaml ]; then
            curl -sL https://raw.githubusercontent.com/ramyerubandi1/getversion/main/charts/nginx/Chart.yaml -o charts/nginx/Chart.yaml
          else
            echo "Chart.yaml does not exist in the docs repo. Skipping update."
            exit 0
          fi

      - name: Check if `Chart.yaml` has changed
        id: check_changes
        run: |
          if git diff --quiet charts/nginx/Chart.yaml; then
            echo "No changes detected."
            echo "CHART_UPDATED=false" >> $GITHUB_ENV
          else
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes to `docs`
        if: env.CHART_UPDATED == 'true'
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git commit -am "Sync Chart.yaml from getversion repo"
          git push origin main
