name: Sync Chart.yaml to Another Repo

on:
  push:
    branches:
      - main
    paths:
      - 'Chart.yaml'  # Trigger only when Chart.yaml changes

jobs:
  sync_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `getversion` repository
        uses: actions/checkout@v3
        with:
          repository: ramyerubandi1/getversion
          path: Chart.yaml  # Checkout into a subdirectory

      - name: Checkout `docs` repository
        uses: actions/checkout@v3
        with:
          repository: ramyerubandi1/docs
          token: ${{ secrets.GH_PAT }}  # Ensure this PAT has write access
          path: charts  # Checkout into a subdirectory

      - name: Copy latest `Chart.yaml`
        run: |
          cp Chart.yaml charts/nginx/Chart.yaml

      - name: Check if `Chart.yaml` has changed
        id: check_changes
        run: |
          cd docs
          if git diff --quiet charts/nginx/Chart.yaml; then
            echo "No changes detected."
            echo "CHART_UPDATED=false" >> $GITHUB_ENV
          else
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes to `docs`
        if: env.CHART_UPDATED == 'true'
        run: |
          cd docs
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add charts/nginx/Chart.yaml
          git commit -m "Sync Chart.yaml from getversion repo"
          git push origin main
