name: Check Version Change and Update Docs

on:
  push:
    paths:
      - 'charts/nginx/Chart.yaml'  # Trigger the workflow only if Chart.yaml is changed
  pull_request:
    paths:
      - 'Chart.yaml'  # Trigger the workflow when PR changes Chart.yaml

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from Chart.yaml
        id: extract_version
        run: |
          VERSION=$(yq e '.version' Chart.yaml)
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Checkout docs repository
        uses: actions/checkout@v2
        with:
          repository: 'ramyerubandi1/docs'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: charts/nginx/Chart.yaml

      - name: Update version in docs repository
        run: |
          # Change directory to the docs repository
          
          # Extract the version from the original Chart.yaml
          VERSION=$(yq e '.version' ../../Chart.yaml)
          echo "Updating version to: $VERSION"
          # Update version in the docs' Chart.yaml
          yq e ".version = \"$VERSION\"" -i Chart.yaml
          # Commit and push the change
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Chart.yaml
          git commit -m "Update version to $VERSION in Chart.yaml"
          git push origin main  # Change branch as needed

