name: Sync Chart.yaml Changes to Docs Repo

on:
  push:
    paths:
      - 'Chart.yaml'  # Trigger workflow only if Chart.yaml is changed
    branches:
      - main  # Change this if your default branch is different

jobs:
  sync-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout getversion repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Clone docs repository
      run: |
        git clone https://github.com/ramyerubandi1/docs.git
        cd docs
        git remote set-url origin https://github.com/ramyerubandi1/docs.git

    - name: Ensure target directory exists
      run: |
        mkdir -p docs/charts/nginx  # Ensures the correct directory exists

    - name: Copy Chart.yaml to docs repo
      run: |
        cp Chart.yaml docs/charts/nginx/Chart.yaml

    - name: Commit and push changes to docs repo
      run: |
        cd docs
        git add charts/nginx/Chart.yaml
        git commit -m "Update nginx Chart.yaml from getversion repository" || echo "No changes to commit"
        git push origin main  # Ensure you are pushing to the correct branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
