name: Sync Helm Chart Version

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  sync_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `docs` repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch Chart version from `getversion`
        run: |
          curl -sL https://raw.githubusercontent.com/ramyerubandi1/getversion/main/charts/nginx/Chart.yaml > getversion_chart.yaml
          GETVERSION_VERSION=$(grep 'version:' getversion_chart.yaml | awk '{print $2}')
          echo "GETVERSION_VERSION=$GETVERSION_VERSION" >> $GITHUB_ENV

      - name: Fetch Chart version from `docs`
        run: |
          DOCS_VERSION=$(grep 'version:' charts/nginx/Chart.yaml | awk '{print $2}')
          echo "DOCS_VERSION=$DOCS_VERSION" >> $GITHUB_ENV

      - name: Compare versions and update if needed
        run: |
          if [ "$GETVERSION_VERSION" != "$DOCS_VERSION" ]; then
            echo "Updating Chart.yaml version in docs repo"
            sed -i "s/version: $DOCS_VERSION/version: $GETVERSION_VERSION/" charts/nginx/Chart.yaml
            echo "VERSION_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No update needed"
          fi

      - name: Commit and push changes
        if: env.VERSION_UPDATED == 'true'
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add charts/nginx/Chart.yaml
          git commit -m "Sync Chart.yaml version to ${{ env.GETVERSION_VERSION }}"
          git push origin main
