name: Sync Chart.yaml to docs

on:
  push:
    branches:
      - main
    paths:
      - 'Chart.yaml'  # Trigger only when Chart.yaml changes

jobs:
  sync_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `docs` repository
        uses: actions/checkout@v3
        with:
          repository: ramyerubandi1/docs
          token: ${{ secrets.GH_PAT }}  # Ensure this PAT has write access to docs repo

      - name: Fetch latest `Chart.yaml` from `getversion`
        run: |
          curl -sL https://raw.githubusercontent.com/ramyerubandi1/getversion/main/charts/nginx/Chart.yaml -o new_Chart.yaml

      - name: Compare and update `Chart.yaml` in docs
        run: |
          if ! cmp -s new_Chart.yaml charts/nginx/Chart.yaml; then
            echo "Updating Chart.yaml in docs repository..."
            mv new_Chart.yaml charts/nginx/Chart.yaml
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
          fi

      - name: Commit and push changes to `docs`
        if: env.CHART_UPDATED == 'true'
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add charts/nginx/Chart.yaml
          git commit -m "Sync Chart.yaml from getversion repo"
          git push origin main
